name: Daily Workflow

on:
  workflow_dispatch:

concurrency:
  group: workflow-group
  cancel-in-progress: true

jobs:
  scrape:
    runs-on: ubuntu-latest
    timeout-minutes: 2000
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4
        
      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.10'
          
      - name: Install Dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
          
      - name: Install Playwright for Python
        run: |
          pip install playwright
          python -m playwright install
          python -m playwright install firefox  # Install Firefox browser

      - name: Install Playwright Dependencies
        run: |
          sudo apt-get install -y libdbus-glib-1-2
          sudo apt-get install -y libgtk-3-0 libgdk-pixbuf2.0-0 libxcomposite1 libxdamage1 libxrandr2 libgbm1 libgtk-4-1 libgraphene-1.0-0 libwoff1 libvpx6 libevent-2.1-7 libopus0 libgstallocators-1.0-0 libgstapp-1.0-0 libgstpbutils-1.0-0 libgstaudio-1.0-0 libgstgl-1.0-0 libgsttag-1.0-0 libgstvideo-1.0-0 libgstcodecparsers-1.0-0 libgstfft-1.0-0 libflite1 libflite_usenglish1 libflite_cmu_grapheme_lang1 libflite_cmu_grapheme_lex1 libflite_cmu_indic_lang1 libflite_cmu_indic_lex1 libflite_cmulex1 libflite_cmu_time_awb1 libflite_cmu_us_awb1 libflite_cmu_us_kal16 libflite_cmu_us_kal1 libflite_cmu_us_rms1 libflite_cmu_us_slt1 libavif13 libharfbuzz-icu0 libsecret-1-0 libhyphen0 libmanette-0.2-0 libgles2 libx264-160
          
      - name: Fix PhantomJS Issue
        run: |
          npm uninstall phantomjs-prebuilt
          npm install phantomjs-prebuilt@2.1.13
          npm cache clear --force
          npm install
          
      - name: Debug Environment
        run: |
          python -m playwright --version
          echo $PATH
          
      - name: Run the scraper
        run: |
          python main.py
          
      - name: Upload Logs
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: scraper-logs
          path: scraper.log
          retention-days: 7
      
      - name: Cleanup
        if: always()
        run: |
          rm -rf node_modules
          rm -rf ~/.cache/ms-playwright

