name: Scrape Talabat Groceries - الظهر

on:
  # schedule:
  #   - cron: "0 */6 * * *"  # Runs every 6 hours
  workflow_dispatch:     # Allows manual triggering

jobs:
  scrape:
    runs-on: ubuntu-latest
    
    env:
      AREA_NAME: الظهر
      AREA_URL: https://www.talabat.com/kuwait/groceries/59/dhaher
      GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      TALABAT_GCLOUD_KEY_JSON: ${{ secrets.TALABAT_GCLOUD_KEY_JSON }}
      
    timeout-minutes: 120  # 2 hours, adjust as needed
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          ref: master  # Adjust if your default branch is 'main'

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.10"

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Install Playwright Browsers
        run: |
          python -m playwright install chromium

      - name: Install Playwright System Dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y libdbus-glib-1-2 libgtk-3-0 libgdk-pixbuf2.0-0 libxcomposite1 libxdamage1 libxrandr2 libgbm1 libpcre3 libwoff1 libevent-2.1-7 libopus0 libsecret-1-0 libhyphen0 libgles2 libsoup2.4-1 libvpx-dev
        

      - name: Restore cached progress
        id: cache-restore
        uses: actions/cache/restore@v4
        with:
          path: |
            current_progress_الظهر.json
            scraped_progress_الظهر.json
            output/الظهر.json
            output/الظهر_detailed.xlsx
          # key: talabat-groceries-progress-الظهر-${{ github.run_id }}
          # restore-keys: |
          #   talabat-groceries-progress-الظهر-
          key: talabat-groceries-progress-${{ env.AREA_NAME }}-v2-${{ github.run_id }}
          restore-keys: |
            talabat-groceries-progress-${{ env.AREA_NAME }}-v2-
          

      - name: Run Talabat Groceries Scraper
        # run: |
        #   python main.py --area-name "الظهر" --url "https://www.talabat.com/kuwait/groceries/59/dhaher"
        run: |
          python main.py --area-name "${{ env.AREA_NAME }}" --url "${{ env.AREA_URL }}"
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          TALABAT_GCLOUD_KEY_JSON: ${{ secrets.TALABAT_GCLOUD_KEY_JSON }}
          WEBSHARE_PROXY_USERNAME: ocdjzatk-rotate
          WEBSHARE_PROXY_PASSWORD: 7m26xglp08ta

      - name: Debug file presence
        if: always()
        run: |
          ls -la
          cat current_progress_الظهر.json || echo "current_progress_الظهر.json not found"
          cat scraped_progress_الظهر.json || echo "scraped_progress_الظهر.json not found"
          ls output/الظهر_detailed.xlsx || echo "الظهر_detailed.xlsx not found"

      - name: Commit progress updates
        if: always()
        run: |
          git config --global user.name "GitHub Action"
          git config --global user.email "action@github.com"
          git add current_progress_الظهر.json scraped_progress_الظهر.json output/*.json output/*.xlsx || true
          git commit -m "Update scraper progress for الظهر run ${{ github.run_id }}" || echo "No changes to commit"
          for attempt in 1 2 3; do
            git pull --rebase && git push && break
            echo "Git push failed (attempt $attempt/3), retrying..."
            sleep $((attempt * 5))
          done || echo "Failed to push after 3 attempts"
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Save progress to cache
        if: always()
        uses: actions/cache/save@v4
        with:
          path: |
            current_progress_الظهر.json
            scraped_progress_الظهر.json
            output/الظهر.json
            output/الظهر_detailed.xlsx
          # key: talabat-groceries-progress-الظهر-${{ github.run_id }}
          key: talabat-groceries-progress-${{ env.AREA_NAME }}-v2-${{ github.run_id }}

      - name: Upload progress artifacts
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: talabat-groceries-progress-الظهر
          path: |
            current_progress_الظهر.json
            scraped_progress_الظهر.json
            output/الظهر.json
            output/الظهر_detailed.xlsx
            scraper.log
          retention-days: 7
          if-no-files-found: warn

      - name: Cleanup
        if: always()
        run: |
          rm -rf ~/.cache/ms-playwright
